// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieEntities.Mapping;

namespace MovieEntities.Mapping.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20181115183338_FixSourcePropertyType")]
    partial class FixSourcePropertyType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("MovieEntities.Mapping.Models.MovieRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Classification");

                    b.Property<string>("ContentType");

                    b.Property<bool>("HasBackdrop");

                    b.Property<bool>("HasPoster");

                    b.Property<decimal?>("ImdbRating");

                    b.Property<bool>("OnFree");

                    b.Property<bool>("OnRentPurchase");

                    b.Property<bool>("OnServices");

                    b.Property<DateTime>("ReleasedOn");

                    b.Property<decimal?>("RottenTomatoesRating");

                    b.Property<bool>("Seen");

                    b.Property<string>("Slug");

                    b.Property<string>("Title");

                    b.Property<bool>("Watchlisted");

                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("MovieEntities.Mapping.Models.MovieSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MovieRatingId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MovieRatingId");

                    b.ToTable("Sources");

                    b.HasData(
                        new { Id = 1, Name = "Netflix" },
                        new { Id = 2, Name = "Hulu Plus" },
                        new { Id = 3, Name = "Amazon Prime" }
                    );
                });

            modelBuilder.Entity("MovieEntities.Mapping.Models.MovieSource", b =>
                {
                    b.HasOne("MovieEntities.Mapping.Models.MovieRating")
                        .WithMany("Sources")
                        .HasForeignKey("MovieRatingId");
                });
#pragma warning restore 612, 618
        }
    }
}
